- openml-h2o/pom.xml
The "httpclient" dependency is very popular and used
across many projects. In this case, H2O depends on it
and it conflicted with AWS dependencies when we use
H2O OpenML in Spark jobs on AWS EMR.
This way we make it provided so that it can be decided
by users.
> Make httpclient dependency of H2O provided

- openml-h2o/pom.xml
Summary:
This commit bumps H2O to version 3.22.1.1 so that we can have access to the new Isolation Forest implementation.
It also adds two new dependencies: a javax servlet, required by H2O 3.22, as well as h2o-jetty-9, also required by H2O >3.22 in an embedded scenario, according to:
https://0xdata.atlassian.net/browse/TN-13
> Bump H2O Version to 3.22.1.1

- pom.xml
Summary:
This commit bumps the OpenML API version to 1.0.0. None of the breaking changes in this bump are applied to this repository.
> Bump OpenML Version to 1.0.0

- openml-datarobot/pom.xml
- openml-datarobot/src/main/java/com/feedzai/openml/datarobot/ClassificationBinaryDataRobotModel.java
- openml-datarobot/src/main/java/com/feedzai/openml/datarobot/DataRobotModelCreator.java
- openml-datarobot/src/test/java/com/feedzai/openml/datarobot/DataRobotModelProviderLoadTest.java
Our DataRobot provider was assuming that Jar files contained a "classLabels" field
in the Model class, which would describe the possible target values for the target
variable being predicted.
That is not the case for old DataRobot versions. As DataRobot supports only binary
classification in exported Jars, we thus assume that the values are "0" and "1" in
that order --- i.e., the positive class is the second one, as is typical on binary
classification problems.
> PULSEDEV-26668: Support old DataRobot versions

- openml-datarobot/src/main/java/com/feedzai/openml/datarobot/DataRobotModelCreator.java
Summary:
Use were using the javafx Pair util class, which seems a bit overkill, since we were dependending on javafx just for this. Furthermore, javafx is not
a default java library for all environments, so environments which do not have javafx will fail when using this logic.
The javafx Pair class was replaced by the apache commons lang3 version, which does everything we want, and was already a dependency of our project.
> openml-datarobot: Remove javafx dependency

- README.md
- openml-h2o/src/main/java/com/feedzai/openml/h2o/server/H2OApp.java
- openml-h2o/src/test/java/com/feedzai/openml/h2o/H2OModelProviderTrainTest.java
An additional check was added to verify that the dataset that was
written to disk is not empty, that would cause an error later inside the
h2o code.
> fix PULSEDEV-27633 openml-h2o: Adds more information in case of error

- .travis.yml
> Force Travis CI to run with JDK 8 as otherwise the build is currently failing

- openml-h2o/pom.xml
After analysing the behaviour of the H2O XGBoost algorithm behaviour
while evaluation in some environments, such as Spark Clusters, it was
clear that it was taking too long to perform the model evaluations.
To temporarly fix this problems it was recommended to perform the
evaluations locally, which, for some reason, were much faster.
After some tests in all environments we found that the difference
between the environments was the native backend library that was
being loaded during the XGBoost initialization.
While the local machines were using the `xgboost4j_minimal` native
library, the Cloudera machines were using the `xgboost4j_gpu`.
This alone made the evaluations take around 100x more time to complete.
After removing the native library from the JAR the evaluations
start performing …
> Remove underperforming native libraries

- openml-h2o/pom.xml
- openml-java-utils/pom.xml
- pom.xml
While upgrading guava to version 29-jre some methods where removed. Since we can't release a version with guava upgraded yet we can already remove the use of deprecated methods, and replace it with similar methods.
> Prepare code for more recent versions of Guava

- openml-lightgbm/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMDescriptorUtil.java
- openml-lightgbm/src/main/java/com/feedzai/openml/provider/lightgbm/SWIGResources.java
- openml-lightgbm/src/main/java/com/feedzai/openml/provider/lightgbm/SWIGTrainResources.java
- openml-lightgbm/src/test/java/com/feedzai/openml/provider/lightgbm/TestSchemas.java
Some visibility modifiers were introduced with the port.
This restores the visibility modifiers where appropriate.
This is mainly in the source code, but also includes one of the test schemas that was used for AutoML.
> LightGBM: Restore visibility modifiers.

- pom.xml
Due to this [release issue](https://github.com/feedzai/feedzai-openml-java/issues/33) I'm adding the exec maven plugin version.
I hope that this may fix the problem.
Note: I removed the tag and release regarding 1.0.10 and 1.0.11 because it wasn't published to the [feedzai maven](https://maven.feedzai.com/#nexus-search;gavcom.feedzaiopenml-java~~~~kw,versionexpand) neither [maven central](https://mvnrepository.com/artifact/com.feedzai/openml-java-utils).
> Add exec maven plugin version

- openml-lightgbm-meta-module/openml-lightgbm/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMBinaryClassificationModelTrainer.java
This adds support for multi-threaded train.
It has already been tested and does not harm scores. There was a speed up of 6x in model train (after having the data in-memory).
> [feature] Multi-threaded LightGBM train.

- openml-lightgbm-meta-module/lightgbm-builder/pom.xml
Previously [nexus-staging-maven-plugin](https://javalibs.com/plugin/org.sonatype.plugins/nexus-staging-maven-plugin) was used to deploy LightGBM lib. However, it doesn't provide deploy-file goal as shown in the end of this [error message](https://api.travis-ci.com/v3/job/371422084/log.txt).
Since we already have installed it using maven-install-plugin, this commit changes nexus-staging-maven-plugin to maven-deploy-plugin.
> Fix LightGBM lib deploy plugin

- openml-h2o/src/test/java/com/feedzai/openml/h2o/H2OAlgorithmTestParams.java
- openml-h2o/src/test/java/com/feedzai/openml/h2o/H2OModelProviderTrainTest.java
There are three mandatory parameters that [H2O GLM 3.22.1.X](http://h2o-release.s3.amazonaws.com/h2o/rel-xu/3/docs-website/h2o-docs/data-science/glm.html) doesn't use and [H2O GLM 3.30.0.X](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/glm.html) does:
* theta
* HGLM
* calc_like
This commit adds these three parameters with its default values.
Added UT to ensure that all algorithms have the mandatory parameters
With the above UT, we discover that there are four mandatory parameters that [H2O Isolation Forest 3.22.1.X](http://h2o-release.s3.amazonaws.com/h2o/rel-xu/3/docs-website/h2o-docs/data-science/if.html) already provided and we didn't add it.
* mtries
* sample_rate
* max_depth
* min_rows
This commit also adds these four parameters with its default values.
> Add H2O GLM mandatory properties with default values for tests

- openml-lightgbm/lightgbm-builder/pom.xml
- openml-lightgbm/lightgbm-provider/pom.xml
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMBinaryClassificationModelTrainer.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMModelCreator.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMSWIG.java
- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/LightGBMBinaryClassificationModelTrainerTest.java
- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/LightGBMModelCreatorTest.java
- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/TestSchemas.java
* Upgrade to LightGBM v3.0.0
* The just released v3.0.0 allows UTF-8 feature names
* Change scoring code to support new prediction API
* Works correctly: wrong start iterations fail the tests
* Prevent future regression: Add test ensuring model fits when using UTF-8 feature names
> LightGBM: Upgrade to v3.0.0 and support UTF-8 feature names

- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMBinaryClassificationModel.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMSWIG.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/SWIGResources.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/SWIGTrainResources.java
- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/SWIGResourcesTest.java
- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/SWIGTrainResourcesTest.java
* Use the newer prediction *Fast() methods and FastConfig
* Reduce temporary object creation (less GC in prediction for better latencies)
* Number of features in prediction classes is now computed from the model (cleaner)
* Visibility refactor for methods in the SWIG helper classes
* Add SWIGResourcesTest and SWIGResourcesTest classes to test resource initialization/release
* Found and fixed 2 double free bugs in SWIGResources
* Instead of hardcoded in LightGBMSWIG, LightGBM prediction parameters are passed to the constructor
> LightGBM: Upgrade to Fast Predict API and fix double free bug

- openml-lightgbm/lightgbm-builder/javadoc/README.md
- openml-lightgbm/lightgbm-builder/pom.xml
- openml-lightgbm/lightgbm-provider/pom.xml
- openml-lightgbm/lightgbm-provider/src/assembly/dist.xml
The commit ad56167 from MR #47 deploys lightgbm-lib as an independent jar to the remote repository. Which wasn't desired.
This commit amends the previous undesired behaviour by:
1. including ligthgmb-lib in the uber jar;
1. making lightgbm-lib non-transitive.
This way prevents to deploy to a remote repository.
> Fix missing lightgbm dependencies on uber jar

- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMBinaryClassificationModel.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMModelCreator.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMSWIG.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/SWIGResources.java
- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/LightGBMModelCreatorTest.java
Additional validation step on `loadModel` ensures schema predictive field names match model booster feature names.
* The implementation assumes that model booster features representation, replaces whitespaces with underscores
* The error scenario was tested with the existing numerical schema with unordered features
> LightGBM: Validate Feature Names on Model Import

- openml-datarobot/pom.xml
- openml-h2o/pom.xml
- openml-java-utils/pom.xml
- openml-lightgbm/lightgbm-provider/pom.xml
- pom.xml
This commit upgrades OpenML and also upgrades Guava to version 25.1.
It changes the `Guava` dependency to scope `compile` so it is bundled in the generated Uber Jars.
And also adds some missing dependencies that were being used without being declared like:
`com.google.code.gson:gson`
`org.slf4j:slf4j-api`
`org.apache.commons:commons-lang3`
and `ch.qos.logback:logback-classic`
> pom: Bump openml-api which now uses Guava 25.1 and add missing dependencies

- pom.xml
This commit upgrades log4j from version 1.2.17 to 1.2.17-cloudera1, since the
older version had some CVEs.
Note that, even though we haven't declared the log4j dependency before, we were
using it since it was a transitive dependency from `ai.h2o:h2o-core`.
> pom: Bump log4j to version 1.2.17-cloudera1

- openml-h2o/pom.xml
This commit removes Kotlin dependency from the shaded jar as it conflicts with the other libraries that use a more up-to-date version.
> Remove kotlin dependency from the shaded jar

- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/SWIGChunkedArrayAPITest.java
SWIGChunkedArrayAPITest uses low-level C++ features without calling the provider
which usually handles the loading of the LGBM libraries for us.
This PR fixes it by loading the libraries explicitly.
> [fix] LightGBM: Load libs in SWIGChunkedArrayAPITest

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .mvn/jgitver.config.xml
jgitver was not comuting versions correctly since Github Actions didn't fetch the necessary tags.
This commit corrects the issue for the tags.
**Experimental tags were removed as they are not supported by jgitver (they should be based on the branch with a different action yaml).** - They were not working properly on TravisCI either.
> Fix jgitver version computation

- .mvn/custom-settings.xml
- .mvn/maven.config
New maven versions block HTTP repositories and this is causing the builds to fail as some dependencies cannot be downloaded by the git CI.
This PR attempts to fix this by using the approach described in https://stackoverflow.com/questions/67001968/how-to-disable-maven-blocking-external-http-repositores/67002852#67002852
> ref PULSEDEV-35240 mvn configuration : Added custom maven settings to unblock http repository

- openml-h2o/pom.xml
- pom.xml
- Bump httpclient from 4.5.5 to 4.5.13 in /openml-h2o
- Update make-lightgbm submodule
- Bump commons-io from 2.4 to 2.7
> ft ml PULSEDEV 35849 bump in hf 1 1 X

- pom.xml
Since it was crashing the build in github actions because mvn no longer
allows usage of insecure http repositories. For that reason, we bumped
from [log4j](https://mvnrepository.com/artifact/log4j/log4j/1.2.17-cloudera1) to [log4j-core](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.14.1)
> Remove usage of http maven icm repository.

- openml-h2o/pom.xml
- pom.xml
- Bump httpclient from 4.5.5 to 4.5.13 in /openml-h2o
- Update make-lightgbm submodule
- Bump commons-io from 2.4 to 2.7
> ft ml PULSEDEV 35849 bump in hf 1 0 X

- openml-h2o/pom.xml
- pom.xml
- Bump httpclient from 4.5.5 to 4.5.13 in /openml-h2o
- Update make-lightgbm submodule
- Bump commons-io from 2.4 to 2.7
- Since it was crashing the build in github actions because mvn no longer
allows usage of insecure http repositories. For that reason, we bumped
from [log4j](https://mvnrepository.com/artifact/log4j/log4j/1.2.17-cloudera1) to [log4j-core](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.14.1)
> ft ml PULSEDEV 35849 bump in hf 1 2 X

- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMDescriptorUtil.java
Makes parameters non-mandatory, because they have default values defined and therefore there is no need to override them.
Besides, turns the descriptors into public so that users can easily access the parameter names. Having them as private was causing the workaround to write the parameter names manually.
> Make all LGBM parameters non-mandatory and turn their descriptors public

- openml-datarobot/pom.xml
- openml-h2o/pom.xml
- openml-h2o/src/main/java/com/feedzai/openml/h2o/H2OModelCreator.java
- openml-h2o/src/test/java/com/feedzai/openml/h2o/H2OModelProviderTrainTest.java
- openml-h2o/src/test/java/com/feedzai/openml/h2o/algos/ParametersTest.java
- openml-java-utils/pom.xml
- openml-java-utils/src/main/java/com/feedzai/openml/java/utils/ModelParameterUtils.java
- openml-java-utils/src/test/java/com/feedzai/openml/java/utils/ModelParameterUtilsTest.java
- pom.xml
Some CVEs were found in the OpenML provider of H2o.
In order to fix them the version of H2o was upgraded from 3.30.0.7 to 3.36.0.3.
That allowed to easily bump the versions of log4j to 2.17.1 and of jetty to 9.4.44.v20210927.
CVE | Component | Version | Location | Security Riska
-- | -- | -- | -- | --
CVE-2020-27216 | jetty-client | 9.4.11.v20180605 | ./pulse-aws/pulse/lib/com.feedzai.openml-h2o-1.1.0.jar | High
CVE-2020-27216 | jetty-continuation | 9.4.11.v20180605 | ./pulse-aws/pulse/lib/com.feedzai.openml-h2o-1.1.0.jar | High
CVE-2020-27216 | jetty-http | 9.4.11.v20180605 | ./pulse-aws/pulse/lib/com.feedzai.openml-h2o-1.1.0.jar | High
CVE-2020-27216 | jetty-io | 9.4.11.v20180605 | ./pulse-aws/pulse/lib/com.feedzai.openml-h2o-1.1.0.jar | High
CVE-2020-27216 | jetty-jaas | …
> Bump jetty and log4j in H2O provider to avoid CVEs

- openml-h2o/src/main/java/com/feedzai/openml/h2o/H2OModelCreator.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/algos/H2OAlgoUtilsFactory.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/algos/H2OBayesUtils.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/algos/H2ODeepLearningUtils.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/algos/H2ODrfUtils.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/algos/H2OGbmUtils.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/algos/H2OGeneralizedLinearModelUtils.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/algos/H2OIsolationForestUtils.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/algos/H2OXgboostUtils.java
- openml-h2o/src/main/java/com/feedzai/openml/h2o/params/ParametersBuilderUtil.java
- openml-h2o/src/test/java/com/feedzai/openml/h2o/H2OAlgorithmTestParams.java
- openml-h2o/src/test/java/com/feedzai/openml/h2o/H2OModelParamTest.java
- openml-java-utils/src/main/java/com/feedzai/openml/java/utils/ModelParameterUtils.java
- openml-java-utils/src/test/java/com/feedzai/openml/java/utils/ModelParameterUtilsTest.java
The previous commit https://github.com/feedzai/feedzai-openml-java/pull/102 introduced a bug where the it was only possible to configure model parameters if they were inside the collection of default model parameters.
This caused a problem because the collection of default model parameters doesn't include all possible model parameters, because some are being filtered due to unsupported types and other reasons.
That problem is now fixed by having a second collection with the names of all possible model parameters, that is then used to get the effective model parameters to be used by the H2o provider.
> Fix validation when training H2o models

- openml-h2o/pom.xml
- pom.xml
After the upgrade of log4j the logs from product started presenting the following logs.
```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier …
```
> Fix unrecognized format specifier

- openml-h2o/pom.xml
- pom.xml
The fix merged in [109](https://github.com/feedzai/feedzai-openml-java/pull/109) caused a random failure when training xgboost models.
The failure was also caused by the bump of log4j and most likely is due to different versions being picked first by the Java class loader.
The solution was to go back to the initial solution proposed in the PR mentioned above.
> Fix unrecognized format specifier when training xgboost models

- openml-h2o/pom.xml
This commit reverts the shaded Kotlin removal.
> ref RAILGUN-930 openml-h2o: Revert "Remove kotlin dependency from the shaded jar (#60)"

- openml-lightgbm/lightgbm-builder/pom.xml
- openml-lightgbm/lightgbm-provider/pom.xml
We were using the main fairgbm branch, `main-fairgbm`; but we should be using a  pinned version.
We are now using the tagged version of FairGBM, `fairgbm-v1.0.0` (pointing to the exact same commit as previously -- the current HEAD of `main-fairgbm`).
> Pin FairGBM artifact version to fairgbm-v1.0.0

- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMDescriptorUtil.java
This field was changed to mandatory when it should be non mandatory. This commit reverts that making the `isMandatory` false again.
>  ref PULSEDEV-37658 openml-lightgbm : Reverted change to learning_rate that made it mandatory

- README.md
Due to a problem/mistake releasing the experimental for version 1.4.1, version 1.4.9999 was released instead of 1.4.9999-snapshot.
This commit documents the proper way of releasing experimentals for this repository so that the same situation does not happen in the future.
> Document experimental releases in README

- .github/workflows/build.yml
- README.md
- openml-lightgbm/lightgbm-builder/pom.xml
- openml-lightgbm/lightgbm-provider/pom.xml
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/Infrastructure.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LibcImplementation.java
- openml-lightgbm/lightgbm-provider/src/main/java/com/feedzai/openml/provider/lightgbm/LightGBMUtils.java
- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/TestInfrastructure.java
- openml-lightgbm/lightgbm-provider/src/test/java/com/feedzai/openml/provider/lightgbm/TestLibcImplementation.java
- pom.xml
This commit bumps lightgbm to v0.9.14 and makes it possible to use LGBM on nodes with AMD64 architecture using Alpine.
> Add support for Alpine on LGBM
